apiVersion: v1
version: 0.0.2
appVersion: 0.0.1
name: test-app
description: An application using a remote parent Helm chart dependency
type: application
dependencies:
- name: app-helm-chart
  version: "0.0.3"
  # repository: file://../../app-helm-chart
  repository: "https://ryanwholey.github.io/helm-charts/"
