name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ryanwholey/${{ github.event.repository.name }}:${{ github.sha }}
  update:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Install yq
        uses: freenet-actions/setup-yq@v2
        with:
          version: 4.9.1
      - name: Update image
        run: yq e --null-input '.app-helm-chart.image.tag = "${{ github.sha }}"' > .deploy/image.yml
      - name: Commit to release branch
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: GitHub Actions updating image version to ${{ github.sha }}
          push: true
